name: Release jpackage GUI App

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact-name: SimpleNotepad-macos
            installer-type: dmg
            installer-suffix: ".dmg"
          - os: windows-latest
            artifact-name: SimpleNotepad-windows
            installer-type: msi
            installer-suffix: ".msi"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'

      - uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

      - run: ./gradlew jpackageImage
        working-directory: jpackage

      - run: ./gradlew jpackage
        working-directory: jpackage
        if: runner.os == 'macOS'

      - run: ./gradlew jpackage
        working-directory: jpackage
        if: runner.os == 'Windows'

      - name: Find installer file (macOS)
        if: runner.os == 'macOS'
        working-directory: jpackage
        run: |
          INSTALLER_FILE=$(find build/jpackage -name "*.dmg" | head -1)
          echo "INSTALLER_PATH=jpackage/$INSTALLER_FILE" >> $GITHUB_ENV
          echo "INSTALLER_NAME=$(basename "$INSTALLER_FILE")" >> $GITHUB_ENV

      - name: Find installer file (Windows)
        if: runner.os == 'Windows'
        working-directory: jpackage
        shell: powershell
        run: |
          $installerFile = Get-ChildItem -Path "build\jpackage" -Filter "*.msi" | Select-Object -First 1
          echo "INSTALLER_PATH=$($installerFile.FullName)" >> $env:GITHUB_ENV
          echo "INSTALLER_NAME=$($installerFile.Name)" >> $env:GITHUB_ENV

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp "${{ env.INSTALLER_PATH }}" "artifacts/${{ matrix.artifact-name }}${{ matrix.installer-suffix }}"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/${{ matrix.artifact-name }}${{ matrix.installer-suffix }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0

      - uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: |
            SimpleNotepad-macos/SimpleNotepad-macos.dmg
            SimpleNotepad-windows/SimpleNotepad-windows.msi
          generate_release_notes: true
