name: Release Native Image CLI

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact-name: jls-linux
            executable-suffix: ""
          - os: macos-latest
            artifact-name: jls-macos
            executable-suffix: ""
          - os: windows-latest
            artifact-name: jls-windows
            executable-suffix: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: graalvm/setup-graalvm@e1df20a713a4cc6ab5b0eb03f0e0dcdc0199b805 # v1.3.4
        with:
          java-version: '24'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      - run: ./gradlew nativeCompile
        working-directory: native-image

      - name: Prepare artifacts (Unix)
        if: runner.os != 'Windows'
        working-directory: native-image
        run: |
          mkdir -p artifacts
          cp build/native/nativeCompile/jls artifacts/${{ matrix.artifact-name }}${{ matrix.executable-suffix }}

      - name: Prepare artifacts (Windows)
        if: runner.os == 'Windows'
        working-directory: native-image
        shell: cmd
        run: |
          mkdir artifacts
          copy build\native\nativeCompile\jls.exe artifacts\${{ matrix.artifact-name }}${{ matrix.executable-suffix }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.artifact-name }}
          path: native-image/artifacts/${{ matrix.artifact-name }}${{ matrix.executable-suffix }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0

      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            jls-linux/jls-linux
            jls-macos/jls-macos
            jls-windows/jls-windows.exe
          generate_release_notes: true
